# Ejercicio 5: Espacio Vectorial
**Objetivo de la práctica**
Implementar un Sistema de Recuperación de Información completo, desde la lectura del corpus hasta la recuperación de resultados.

## Parte 0: Carga del Corpus
Carga el corpus y realiza las etapas de preprocesamiento (limpieza, tokenización, stemming).

In [1]:
import pandas as pd
import numpy as np
import re
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer

# Para evitar tiempos excesivos de procesamiento en el ejercicio, limitamos el dataset
LIMIT = 1000 

# Carga el corpus
print("Cargando dataset...")
df_corpus = pd.read_csv(
    'wikipedia_text_corpus.csv',
    nrows=LIMIT
)

print(f"Corpus cargado con {len(df_corpus)} documentos.")

display(df_corpus.head())

Cargando dataset...
Corpus cargado con 1000 documentos.

   Unnamed: 0                                               text
0           1  Anovo\n\nAnovo (formerly A Novo) is a computer...
1           2  Battery indicator\n\nA battery indicator (also...
2           3  Bob Pease\n\nRobert Allen Pease (August 22, 19...
3           4  CAVNET\n\nCAVNET was a secure military forum w...
4           5  CLidar\n\nThe CLidar is a scientific instrumen...

In [2]:
# Función para procesar cada documento (como en limpieza.ipynb)

stemmer = PorterStemmer()

def process_document(text):
    # Validar que el dato sea texto
    if not isinstance(text, str):
        return ""

    # Eliminar caracteres especiales
    cleaned = re.sub(r'[^\w\s]', ' ', text)

    # Eliminar números
    cleaned = re.sub(r'\d+', '', cleaned)

    # Convertir a minúsculas
    cleaned = cleaned.lower()

    # Tokenización simple
    tokens = cleaned.split()

    # Aplicar stemming
    stemmed_tokens = [stemmer.stem(token) for token in tokens]

    # Unir nuevamente como texto
    return ' '.join(stemmed_tokens)


print("Iniciando el preprocesamiento (Limpieza, Tokenización, Stemming)...")
df_corpus['processed'] = df_corpus['text'].apply(process_document)
print("Preprocesamiento completado.")
display(df_corpus[['text', 'processed']].head())

Iniciando el preprocesamiento (Limpieza, Tokenización, Stemming)...

Preprocesamiento completado.

,text,processed
0,Anovo\n\nAnovo (formerly A Novo) is a computer...,anovo anovo formerli a novo is a comput servic...
1,Battery indicator\n\nA battery indicator (also...,batteri indic a batteri indic also known as a ...
2,"Bob Pease\n\nRobert Allen Pease (August 22, 19...",bob peas robert allen peas august â â june wa ...
3,CAVNET\n\nCAVNET was a secure military forum w...,cavnet cavnet wa a secur militari forum which ...
4,CLidar\n\nThe CLidar is a scientific instrumen...,clidar the clidar is a scientif instrument use...

## Parte 1: Recuperación con TF-IDF
Obtén la representación vectorial de los documentos utilizando el modelo TF-IDF.

In [3]:
# Crear el vectorizador TF-IDF y transformar el corpus procesado
vectorizer_tfidf = TfidfVectorizer()
tfidf_matrix = vectorizer_tfidf.fit_transform(df_corpus['processed'])

print(f"Matriz TF-IDF creada con forma: {tfidf_matrix.shape}")

Matriz TF-IDF creada con forma: (1000, 25472)

In [4]:
from sklearn.metrics.pairwise import cosine_similarity

# Conjunto de 10 queries
queries = [
    "artificial intelligence computer",
    "history of the world",
    "global warming and climate change",
    "how to play video games",
    "space exploration and mars",
    "electric vehicles energy",
    "united states politics",
    "the immune system health",
    "famous classical music composers",
    "stock market trends economy"
]

def search_tfidf(query, vectorizer, matrix, df, top_k=5):
    query_processed = process_document(query)
    query_vector = vectorizer.transform([query_processed])
    similarities = cosine_similarity(query_vector, matrix)[0]
    
    # Obtener los top_k índices (ordenados de mayor a menor)
    top_indices = similarities.argsort()[-top_k:][::-1]
    
    results = []
    for idx in top_indices:
        # Solo agregar si hay algo de similitud
        if similarities[idx] > 0:
            results.append({
                'doc_id': idx,
                'score': similarities[idx],
                'text': df.iloc[idx]['text'][:150].replace('\n', ' ') + "..."
            })
    return results

# Verificar la recuperación del sistema
print("=== Búsqueda usando TF-IDF ===")
for i, q in enumerate(queries):
    print(f"\n--- Query {i+1}: '{q}' ---")
    results = search_tfidf(q, vectorizer_tfidf, tfidf_matrix, df_corpus)
    if not results:
        print("No se encontraron documentos relevantes.")
    for r in results:
        print(f"Doc ID: {r['doc_id']:<4} | Similitud: {r['score']:.4f} | Texto: {r['text']}")

=== Búsqueda usando TF-IDF ===

--- Query 1: 'artificial intelligence computer' ---
Doc ID: 485  | Similitud: 0.3430 | Texto: Strategic Computing Initiative  The United States government's Strategic Computing Initiative funded research into advanced computer hardware and arti...
Doc ID: 669  | Similitud: 0.2897 | Texto: Open Letter on Artificial Intelligence  In January 2015, Stephen Hawking, Elon Musk, and dozens of artificial intelligence experts signed an open lett...
Doc ID: 671  | Similitud: 0.1805 | Texto: Organizational intelligence  Organizational Intelligence (OI) is the capability of an organization to comprehend and conclude knowledge relevant to it...
Doc ID: 996  | Similitud: 0.1594 | Texto: Computer-aided maintenance  Computer-aided maintenance (not to be confused with CAM which usually stands for Computer Aided Manufacturing) refers to s...
Doc ID: 120  | Similitud: 0.1593 | Texto: List of computer books  Computer fundamentals by bikramjit nath    ...

--- Query 2: 'history of the world' ---
Doc ID: 430  | Similitud: 0.2488 | Texto: Power history  Power History refers to the power of a nuclear reactor over an extended period of time. Power history is important for calculations and...
Doc ID: 338  | Similitud: 0.2423 | Texto: Textile History  Textile History is a peer-reviewed academic journal first published in 1968 and published by Maney Publishing on behalf of the Pasold...
Doc ID: 515  | Similitud: 0.2281 | Texto: Leonardo da Vinci Medal  The Leonardo da Vinci Medal is the highest award of the Society for the History of Technology (SHOT) established in 1962. In ...
Doc ID: 464  | Similitud: 0.2150 | Texto: History of aviation  The history of aviation extends for more than two thousand years, from the earliest forms of aviation such as kites and attempts ...
Doc ID: 915  | Similitud: 0.2027 | Texto: List of World War II weapons  World War II saw rapid technological innovation in response to the needs of the various combatants. Many different weapo...

--- Query 3: 'global warming and climate change' ---
Doc ID: 941  | Similitud: 0.2770 | Texto: Climatic Research Unit email controversy  The Climatic Research Unit email controversy (also known as "Climategate") began in November 2009 with the h...
Doc ID: 311  | Similitud: 0.2719 | Texto: Global information system  There are a variety of definitions and understandings of a global information system (GIS, GLIS), such as    Common to this...
Doc ID: 954  | Similitud: 0.1950 | Texto: Hindou Oumarou Ibrahim  Hindou Oumarou Ibrahim is an environmental activist and geographer. She is the Coordinator of the Association of Peul Women an...
Doc ID: 843  | Similitud: 0.1395 | Texto: Change detection (GIS)  Change detection for GIS (geographical information systems) is a process that measures how the attributes of a particular area...
Doc ID: 653  | Similitud: 0.1138 | Texto: Information Technology Industry Council  The Information Technology Industry Council (ITI) is a Washington, D.C.-based trade association that represen...

--- Query 4: 'how to play video games' ---
Doc ID: 611  | Similitud: 0.3490 | Texto: InLiving  InLiving is an educational game focusing on independent living. Aimed at young people aged 13â€“25, the game has been developed by Creative ...
Doc ID: 384  | Similitud: 0.3113 | Texto: Pyro Studios  Pyro Mobile is a video game developer based in Madrid, Spain, established in 2012 as a merger between Play Wireless and Pyro Studios, mo...
Doc ID: 606  | Similitud: 0.2460 | Texto: Entertainment Consumers Association  Entertainment Consumers Association (ECA) is a United States-based non-partisan, non-government, non-profit organ...
Doc ID: 394  | Similitud: 0.1975 | Texto: Accel World  Haruyuki "Haru" Arita is a short, overweight boy who is frequently ridiculed by delinquents at the Umesato Junior High School. Using his ...
Doc ID: 523  | Similitud: 0.1903 | Texto: Network video recorder  A network video recorder (NVR) is a specialized computer system that includes a software program that records video in a digit...

--- Query 5: 'space exploration and mars' ---
Doc ID: 759  | Similitud: 0.2215 | Texto: History of spaceflight  Spaceflight began in the 20th century following theoretical and practical breakthroughs by Konstantin Tsiolkovsky and Robert H...
Doc ID: 685  | Similitud: 0.1252 | Texto: Stephanie Wilson  Stephanie Diana Wilson (born September 27, 1966) is an American engineer and a NASA astronaut. She flew to space onboard three Space...
Doc ID: 230  | Similitud: 0.0988 | Texto: MULTICUBE  "Multi-objective Design Space Exploration of MultiProcessor-SoC Architectures for Embedded Multimedia Applications" (MULTICUBE)  is a Seven...
Doc ID: 807  | Similitud: 0.0916 | Texto: Mika McKinnon  Mika McKinnon is a Canadian field geophysicist, disaster researcher, and science communicator. She is currently a co-investigator of th...
Doc ID: 492  | Similitud: 0.0866 | Texto: Artificial gravity  Artificial gravity (sometimes referred to as pseudogravity) is the creation of an inertial force that mimics the effects of a grav...

--- Query 6: 'electric vehicles energy' ---
Doc ID: 993  | Similitud: 0.5182 | Texto: Battery electric vehicle  A battery electric vehicle (BEV), pure electric vehicle or all-electric vehicle is a type of electric vehicle (EV) that uses...
Doc ID: 86   | Similitud: 0.4621 | Texto: Motor vehicle  A motor vehicle, also known as motorized vehicle or automotive vehicle, is a self-propelled vehicle, commonly wheeled, that does not op...
Doc ID: 719  | Similitud: 0.4134 | Texto: Outline of vehicles  The following outline is provided as an overview of and topical guide to vehicles:  Vehicle â€“ non-living means of transportatio...
Doc ID: 462  | Similitud: 0.3284 | Texto: Federal Energy Agency (Russia)  Russian Energy Agency is a federal state budgetary organization under the Ministry of Energy of the Russian Federation...
Doc ID: 563  | Similitud: 0.2856 | Texto: Hybrid vehicle drivetrain  Hybrid vehicle drivetrains transmit power to the driving wheels for hybrid vehicles. A hybrid vehicle has multiple forms of...

--- Query 7: 'united states politics' ---
Doc ID: 116  | Similitud: 0.1193 | Texto: Global Internet Freedom Consortium  The Global Internet Freedom Consortium is a consortium of organizations that develop and deploy anti-censorship te...
Doc ID: 92   | Similitud: 0.0961 | Texto: Taxation of digital goods  Digital goods are software programs, music, videos or other electronic files that users download exclusively from the Inter...
Doc ID: 44   | Similitud: 0.0937 | Texto: U.S. Army hand and arm signals  Hand and arm signals for United States Army use were first laid down in Field Manual 21-60. They were superseded in Tr...
Doc ID: 298  | Similitud: 0.0754 | Texto: CBU-72  The CBU-72 was a 550-pound American fuel-air cluster bomb used by the United States Military until 1996. It was very effective against armored...
Doc ID: 433  | Similitud: 0.0734 | Texto: Radio Technical Commission for Aeronautics  RTCA, Inc., formerly known as (Radio Technical Commission for Aeronautics), is a United States volunteer o...

--- Query 8: 'the immune system health' ---
Doc ID: 387  | Similitud: 0.2517 | Texto: Syneos Health  Syneos Health (formerly InVentiv Health Incorporated and INC Research) is a NASDAQ listed American multinational clinical studies contr...
Doc ID: 851  | Similitud: 0.1797 | Texto: Hacking Health  Hacking Health is a social organization that pairs innovators with healthcare experts to build solutions to front-line healthcare prob...
Doc ID: 599  | Similitud: 0.1647 | Texto: Bio-Synthesis, Inc.  Bio-Synthesis, Inc. (BSI) is a biotechnology company headquartered in Lewisville, Texas. It is a provider of custom and catalog p...
Doc ID: 174  | Similitud: 0.1577 | Texto: Information system  Information systems (IS) are formal, sociotechnical, organizational systems designed to collect, process, store, and distribute in...
Doc ID: 356  | Similitud: 0.1373 | Texto: Femtech  Femtech (or Female technology) is a term applied to a category of software, diagnostics, products, and services that use technology often to ...

--- Query 9: 'famous classical music composers' ---
Doc ID: 762  | Similitud: 0.2247 | Texto: International Society for Music Information Retrieval  The International Society for Music Information Retrieval (ISMIR) is an international forum for...
Doc ID: 792  | Similitud: 0.1823 | Texto: Delia Derbyshire  Delia Ann Derbyshire (5 May 1937Â â€“ 3 July 2001) was an English musician and composer of electronic music. She is best known for h...
Doc ID: 320  | Similitud: 0.1649 | Texto: Mosaic notation program  Mosaic (also called Composer's Mosaic) was a Macintosh scorewriter application for producing music notation, developed by Mar...
Doc ID: 373  | Similitud: 0.1594 | Texto: Normand Roger  Normand Roger (born 1949 in Montreal, Quebec) is a Canadian composer, sound editor and sound designer. He is particularly known for his...
Doc ID: 794  | Similitud: 0.0948 | Texto: French Restoration style  The French Restoration style was predominantly Neoclassicism, though it also showed the beginnings of romanticism in music a...

--- Query 10: 'stock market trends economy' ---
Doc ID: 819  | Similitud: 0.1855 | Texto: SUMCO  SUMCO is listed on the first section of the Tokyo Stock Exchange and is a constituent of the Nikkei 225 stock index.  The company manufactures ...
Doc ID: 269  | Similitud: 0.1303 | Texto: Kemao Market  Kemao Market is one of five major electronics markets in Zhongguancun, Beijing.  Kemao Market opened its doors on 2004-02-21. The buildi...
Doc ID: 188  | Similitud: 0.1058 | Texto: Proto-industrialization  Proto-industrialization (also spelled proto-industrialisation) was a possible phase in the development of modern industrial e...
Doc ID: 108  | Similitud: 0.0899 | Texto: Day trading software  Day trading software is computer software intended to facilitate day trading of stocks or other financial instruments.  Day trad...
Doc ID: 462  | Similitud: 0.0870 | Texto: Federal Energy Agency (Russia)  Russian Energy Agency is a federal state budgetary organization under the Ministry of Energy of the Russian Federation...

## Parte 2: Recuperación con BM25
Implementa un sistema de recuperación usando el modelo BM25.

In [5]:
# !pip install rank_bm25
from rank_bm25 import BM25Okapi

# BM25 requiere los documentos como listas de tokens (ya procesados)
tokenized_corpus = [doc.split() for doc in df_corpus['processed']]

bm25 = BM25Okapi(tokenized_corpus)

def search_bm25(query, bm25_model, df, top_k=5):
    query_processed = process_document(query)
    query_tokens = query_processed.split()
    
    doc_scores = bm25_model.get_scores(query_tokens)
    
    # Obtener los top_k índices
    top_indices = doc_scores.argsort()[-top_k:][::-1]
    
    results = []
    for idx in top_indices:
        if doc_scores[idx] > 0:
            results.append({
                'doc_id': idx,
                'score': doc_scores[idx],
                'text': df.iloc[idx]['text'][:150].replace('\n', ' ') + "..."
            })
    return results

# Verificar la recuperación
print("=== Búsqueda usando BM25 ===")
for i, q in enumerate(queries):
    print(f"\n--- Query {i+1}: '{q}' ---")
    results = search_bm25(q, bm25, df_corpus)
    if not results:
        print("No se encontraron documentos relevantes.")
    for r in results:
        print(f"Doc ID: {r['doc_id']:<4} | Score: {r['score']:.4f} | Texto: {r['text']}")

=== Búsqueda usando BM25 ===

--- Query 1: 'artificial intelligence computer' ---
Doc ID: 485  | Score: 15.3722 | Texto: Strategic Computing Initiative  The United States government's Strategic Computing Initiative funded research into advanced computer hardware and arti...
Doc ID: 669  | Score: 14.6849 | Texto: Open Letter on Artificial Intelligence  In January 2015, Stephen Hawking, Elon Musk, and dozens of artificial intelligence experts signed an open lett...
Doc ID: 265  | Score: 12.3963 | Texto: ILabs  iLabs is a non-profit Milan-based organization pursuing multidisciplinary research on radical extension of human life-span. It was founded in 1...
Doc ID: 996  | Score: 11.4551 | Texto: Computer-aided maintenance  Computer-aided maintenance (not to be confused with CAM which usually stands for Computer Aided Manufacturing) refers to s...
Doc ID: 862  | Score: 10.8409 | Texto: Liz Bacon  Liz Bacon (born 27 September 1963) is a Professor of Software Engineering and Deputy Pro Vice-Chancellor at the University of Greenwich, En...

--- Query 2: 'history of the world' ---
Doc ID: 150  | Score: 12.3630 | Texto: Alsos Digital Library for Nuclear Issues  The Alsos Digital Library for Nuclear Issues is a searchable collection of vetted annotations and bibliograp...
Doc ID: 283  | Score: 12.0283 | Texto: Rudyerd Boulton  Wolfrid Rudyerd Boulton (April 5, 1901 â€“ January 24, 1983) was an American ornithologist who worked extensively in Africa. Boulton ...
Doc ID: 363  | Score: 11.9869 | Texto: Joan Ball  Joan Ball was a computer dating pioneer who started the first computer dating service in England, in 1964. Ball's computer dating service a...
Doc ID: 974  | Score: 11.9257 | Texto: Reem Al Marzouqi  Reem Al Marzouqi ( ) is an Emirati engineer and the first citizen of the UAE to be granted a patent in the United States of America ...
Doc ID: 560  | Score: 11.9194 | Texto: GlobalSantaFe Corporation  GlobalSantaFe Corporation, which traded on the NYSE as GSF was an offshore oil and gas drilling contractor, which owned or ...

--- Query 3: 'global warming and climate change' ---
Doc ID: 941  | Score: 21.7459 | Texto: Climatic Research Unit email controversy  The Climatic Research Unit email controversy (also known as "Climategate") began in November 2009 with the h...
Doc ID: 793  | Score: 17.0925 | Texto: Fossil fuel divestment  Fossil fuel divestment or fossil fuel divestment and investment in climate solutions is the removal of investment assets inclu...
Doc ID: 954  | Score: 16.5284 | Texto: Hindou Oumarou Ibrahim  Hindou Oumarou Ibrahim is an environmental activist and geographer. She is the Coordinator of the Association of Peul Women an...
Doc ID: 6    | Score: 14.6331 | Texto: Carbon Recycling International  Carbon Recycling International - CRI hf. (CRI) is an Icelandic limited liability company which has developed a technol...
Doc ID: 73   | Score: 13.8830 | Texto: Heater core  A heater core is a radiator-like device used in heating the cabin of a vehicle. Hot coolant from the vehicle's engine is passed through a...

--- Query 4: 'how to play video games' ---
Doc ID: 384  | Score: 18.7187 | Texto: Pyro Studios  Pyro Mobile is a video game developer based in Madrid, Spain, established in 2012 as a merger between Play Wireless and Pyro Studios, mo...
Doc ID: 182  | Score: 17.4852 | Texto: Nintendo Labo  Nintendo Labo is released as individual Labo Kits, each containing a set of pre-made cardboard cut-outs and other materials, used to ma...
Doc ID: 394  | Score: 17.2752 | Texto: Accel World  Haruyuki "Haru" Arita is a short, overweight boy who is frequently ridiculed by delinquents at the Umesato Junior High School. Using his ...
Doc ID: 551  | Score: 16.9171 | Texto: Digital locker  A digital locker or cyberlocker is an online file or digital media storage service. Files stored include music, videos, movies, games ...
Doc ID: 606  | Score: 16.2373 | Texto: Entertainment Consumers Association  Entertainment Consumers Association (ECA) is a United States-based non-partisan, non-government, non-profit organ...

--- Query 5: 'space exploration and mars' ---
Doc ID: 759  | Score: 18.3250 | Texto: History of spaceflight  Spaceflight began in the 20th century following theoretical and practical breakthroughs by Konstantin Tsiolkovsky and Robert H...
Doc ID: 492  | Score: 12.8643 | Texto: Artificial gravity  Artificial gravity (sometimes referred to as pseudogravity) is the creation of an inertial force that mimics the effects of a grav...
Doc ID: 230  | Score: 12.1055 | Texto: MULTICUBE  "Multi-objective Design Space Exploration of MultiProcessor-SoC Architectures for Embedded Multimedia Applications" (MULTICUBE)  is a Seven...
Doc ID: 807  | Score: 11.9533 | Texto: Mika McKinnon  Mika McKinnon is a Canadian field geophysicist, disaster researcher, and science communicator. She is currently a co-investigator of th...
Doc ID: 323  | Score: 10.9240 | Texto: Photonic laser thruster  A photonic laser thruster (PLT) is an amplified photonic propulsion thruster for space propulsion that works on the principle...

--- Query 6: 'electric vehicles energy' ---
Doc ID: 993  | Score: 12.3826 | Texto: Battery electric vehicle  A battery electric vehicle (BEV), pure electric vehicle or all-electric vehicle is a type of electric vehicle (EV) that uses...
Doc ID: 563  | Score: 12.0984 | Texto: Hybrid vehicle drivetrain  Hybrid vehicle drivetrains transmit power to the driving wheels for hybrid vehicles. A hybrid vehicle has multiple forms of...
Doc ID: 86   | Score: 9.4450 | Texto: Motor vehicle  A motor vehicle, also known as motorized vehicle or automotive vehicle, is a self-propelled vehicle, commonly wheeled, that does not op...
Doc ID: 949  | Score: 8.7426 | Texto: Free-piston linear generator  The free-piston linear generator (FPLG), is a free-piston engine coupled with a linear alternator. It converts chemical ...
Doc ID: 6    | Score: 8.6044 | Texto: Carbon Recycling International  Carbon Recycling International - CRI hf. (CRI) is an Icelandic limited liability company which has developed a technol...

--- Query 7: 'united states politics' ---
Doc ID: 927  | Score: 7.4245 | Texto: Shai Reshef  Shai Reshef born September 11, 1955 is an Israeli educational entrepreneur, founder and president of University of the People, the world'...
Doc ID: 189  | Score: 6.8218 | Texto: Psychological warfare  Psychological warfare (PSYWAR), or the basic aspects of modern psychological operations (PSYOP), have been known by many other ...
Doc ID: 337  | Score: 6.6056 | Texto: Swords to ploughshares  Swords to ploughshares (or Swords to plowshares) is a concept in which military weapons or technologies are converted for peac...
Doc ID: 173  | Score: 5.8607 | Texto: History of cycling  Cycling quickly became an activity after bicycles were introduced in the 19th century and remains popular with more than a billion...
Doc ID: 833  | Score: 5.7198 | Texto: United Cannery, Agricultural, Packing, and Allied Workers of America  The United Cannery, Agricultural, Packing, and Allied Workers of America (UCAPAW...

--- Query 8: 'the immune system health' ---
Doc ID: 599  | Score: 15.3695 | Texto: Bio-Synthesis, Inc.  Bio-Synthesis, Inc. (BSI) is a biotechnology company headquartered in Lewisville, Texas. It is a provider of custom and catalog p...
Doc ID: 850  | Score: 14.2216 | Texto: HIV vaccine  An HIV vaccine may have the purpose of protecting individuals who do not have HIV from being infected with the virus (a preventive vaccin...
Doc ID: 222  | Score: 11.3476 | Texto: Implant (medicine)  An implant is a medical device manufactured to replace a missing biological structure, support a damaged biological structure, or ...
Doc ID: 308  | Score: 11.2015 | Texto: Exhaust gas  Exhaust gas or flue gas is emitted as a result of the combustion of fuels such as natural gas, gasoline, petrol, biodiesel blends, diesel...
Doc ID: 456  | Score: 11.0666 | Texto: ESD simulator  An ESD simulator, also known as an ESD gun, is a handheld unit used to test the immunity of devices to electrostatic discharge (ESD). T...

--- Query 9: 'famous classical music composers' ---
Doc ID: 794  | Score: 16.6273 | Texto: French Restoration style  The French Restoration style was predominantly Neoclassicism, though it also showed the beginnings of romanticism in music a...
Doc ID: 792  | Score: 13.6418 | Texto: Delia Derbyshire  Delia Ann Derbyshire (5 May 1937Â â€“ 3 July 2001) was an English musician and composer of electronic music. She is best known for h...
Doc ID: 320  | Score: 12.5715 | Texto: Mosaic notation program  Mosaic (also called Composer's Mosaic) was a Macintosh scorewriter application for producing music notation, developed by Mar...
Doc ID: 373  | Score: 12.1558 | Texto: Normand Roger  Normand Roger (born 1949 in Montreal, Quebec) is a Canadian composer, sound editor and sound designer. He is particularly known for his...
Doc ID: 980  | Score: 11.0487 | Texto: The Typewriter  "The Typewriter" is a short composition of light music by American composer Leroy Anderson, which features an actual typewriter as a p...

--- Query 10: 'stock market trends economy' ---
Doc ID: 732  | Score: 9.6625 | Texto: The New Age of Innovation  The New Age of Innovation: Driving Cocreated Value Through Global Networks () is a book by University of Michigan Ross Scho...
Doc ID: 188  | Score: 9.3757 | Texto: Proto-industrialization  Proto-industrialization (also spelled proto-industrialisation) was a possible phase in the development of modern industrial e...
Doc ID: 361  | Score: 9.3235 | Texto: IPC (electronics)  IPC, the Association Connecting Electronics Industries, is a trade association whose aim is to standardize the assembly and product...
Doc ID: 59   | Score: 8.8181 | Texto: ESignal  eSignal, a Windows-based application, uses JavaScript as the basis for the scripting language that programmers and traders can use for buildi...
Doc ID: 265  | Score: 8.6712 | Texto: ILabs  iLabs is a non-profit Milan-based organization pursuing multidisciplinary research on radical extension of human life-span. It was founded in 1...

## Parte 3: Comparación de resultados
Verifica cuáles documentos son recuperados (y en qué orden) por cada modelo de recuperación.

In [6]:
# Comparamos los resultados de ambos algoritmos
for i, q in enumerate(queries):
    print(f"\n" + "="*50)
    print(f"Query {i+1}: '{q}'")
    print("="*50)
    
    res_tfidf = search_tfidf(q, vectorizer_tfidf, tfidf_matrix, df_corpus, top_k=5)
    res_bm25 = search_bm25(q, bm25, df_corpus, top_k=5)
    
    print("{:<25} | {:<25}".format("Recuperación TF-IDF", "Recuperación BM25"))
    print("-"*55)
    
    max_len = max(len(res_tfidf), len(res_bm25))
    for j in range(max_len):
        str_tfidf = f"Doc {res_tfidf[j]['doc_id']} ({res_tfidf[j]['score']:.4f})" if j < len(res_tfidf) else "-"
        str_bm25 = f"Doc {res_bm25[j]['doc_id']} ({res_bm25[j]['score']:.4f})" if j < len(res_bm25) else "-"
        print("{:<25} | {:<25}".format(str_tfidf, str_bm25))

==================================================
Query 1: 'artificial intelligence computer'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 485 (0.3430)          | Doc 485 (15.3722)
Doc 669 (0.2897)          | Doc 669 (14.6849)
Doc 671 (0.1805)          | Doc 265 (12.3963)
Doc 996 (0.1594)          | Doc 996 (11.4551)
Doc 120 (0.1593)          | Doc 862 (10.8409)

==================================================
Query 2: 'history of the world'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 430 (0.2488)          | Doc 150 (12.3630)
Doc 338 (0.2423)          | Doc 283 (12.0283)
Doc 515 (0.2281)          | Doc 363 (11.9869)
Doc 464 (0.2150)          | Doc 974 (11.9257)
Doc 915 (0.2027)          | Doc 560 (11.9194)

==================================================
Query 3: 'global warming and climate change'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 941 (0.2770)          | Doc 941 (21.7459)
Doc 311 (0.2719)          | Doc 793 (17.0925)
Doc 954 (0.1950)          | Doc 954 (16.5284)
Doc 843 (0.1395)          | Doc 6 (14.6331)
Doc 653 (0.1138)          | Doc 73 (13.8830)

==================================================
Query 4: 'how to play video games'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 611 (0.3490)          | Doc 384 (18.7187)
Doc 384 (0.3113)          | Doc 182 (17.4852)
Doc 606 (0.2460)          | Doc 394 (17.2752)
Doc 394 (0.1975)          | Doc 551 (16.9171)
Doc 523 (0.1903)          | Doc 606 (16.2373)

==================================================
Query 5: 'space exploration and mars'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 759 (0.2215)          | Doc 759 (18.3250)
Doc 685 (0.1252)          | Doc 492 (12.8643)
Doc 230 (0.0988)          | Doc 230 (12.1055)
Doc 807 (0.0916)          | Doc 807 (11.9533)
Doc 492 (0.0866)          | Doc 323 (10.9240)

==================================================
Query 6: 'electric vehicles energy'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 993 (0.5182)          | Doc 993 (12.3826)
Doc 86 (0.4621)           | Doc 563 (12.0984)
Doc 719 (0.4134)          | Doc 86 (9.4450)
Doc 462 (0.3284)          | Doc 949 (8.7426)
Doc 563 (0.2856)          | Doc 6 (8.6044)

==================================================
Query 7: 'united states politics'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 116 (0.1193)          | Doc 927 (7.4245)
Doc 92 (0.0961)           | Doc 189 (6.8218)
Doc 44 (0.0937)           | Doc 337 (6.6056)
Doc 298 (0.0754)          | Doc 173 (5.8607)
Doc 433 (0.0734)          | Doc 833 (5.7198)

==================================================
Query 8: 'the immune system health'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 387 (0.2517)          | Doc 599 (15.3695)
Doc 851 (0.1797)          | Doc 850 (14.2216)
Doc 599 (0.1647)          | Doc 222 (11.3476)
Doc 174 (0.1577)          | Doc 308 (11.2015)
Doc 356 (0.1373)          | Doc 456 (11.0666)

==================================================
Query 9: 'famous classical music composers'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 762 (0.2247)          | Doc 794 (16.6273)
Doc 792 (0.1823)          | Doc 792 (13.6418)
Doc 320 (0.1649)          | Doc 320 (12.5715)
Doc 373 (0.1594)          | Doc 373 (12.1558)
Doc 794 (0.0948)          | Doc 980 (11.0487)

==================================================
Query 10: 'stock market trends economy'
==================================================
Recuperación TF-IDF       | Recuperación BM25
-------------------------------------------------------
Doc 819 (0.1855)          | Doc 732 (9.6625)
Doc 269 (0.1303)          | Doc 188 (9.3757)
Doc 188 (0.1058)          | Doc 361 (9.3235)
Doc 108 (0.0899)          | Doc 59 (8.8181)
Doc 462 (0.0870)          | Doc 265 (8.6712)